[project]
requires-python = ">3.7,<3.11"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
# https://github.com/python-versioneer/python-versioneer/issues/192
    "versioneer-518"
]
build-backend = "setuptools.build_meta"