#!/usr/bin/env python3

import sys
import glob
import os

from flask import Flask

from covfee.orm import app, db, Project, Timeline, Task, Chunk
from covfee.utils.autoparser import subparser, test_parser

def create_tables():
    db.create_all()

@subparser
def json(fpath, force: bool=False):
    dbpath = app.config['DATABASE_PATH']
    if force:
        try:
            os.remove(app.config['DATABASE_PATH'])
            print(f'deleted existing database file {app.config["DATABASE_PATH"]}')
        except OSError:
            pass
    create_tables()
    project = Project.from_json(fpath)
    db.session.add(project)
    db.session.commit()
    print(project.info())

@subparser
def load_samples():
    

    try:
        print('creating tables')
        create_tables()
        print('tables created')
    except Exception as e:
        print('error creating tables, aborting')
        print(e)
        exit(1)
    
    for fpath in glob.iglob(f'{PROJECTS_PATH}/*.json'):
        print(f'creating project {fpath}')
        project = Project.from_json(fpath)
        db.session.add(project)

    print('commiting to DB')
    db.session.commit()
    print('done!')

    for proj in projects:
        print(proj.info())

if __name__ == '__main__':
    test_parser(globals())
